# Generated by Django 3.0.8 on 2020-07-09 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
    ]
